---
- name: R1soft Playbook
  hosts: all
  become: true
  become_method: sudo
  connection: ssh
  ignore_errors: false
  tasks:
    - name: Creates a repo
      ping:
      copy: r1soft.repo
      dest: /etc/yum.repos.d/r1soft.repo
      
    - name: Install R1soft
       package: serverbackup-enterprise-agent 
       state: latest

    - name: Power off iptables
      systemd:
         name: firewall 
         state: stopped
      ignore_errors: true 

    - name: Get key
      shell: r1soft-setup --get-key http://backup.aliacavdar.com

    - name: Start R1soft agent
      systemd: 
        name: sbm-agent
        state: restarted
        enabled: yes
        